name: Sandbox Deployment

on:
  push:
    branches:
      - main

concurrency:
  group: sandbox-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sandbox

    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: SSH in server and deploy sandbox branch
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SANDBOX_IP }}
          username: ${{ secrets.SANDBOX_USER }}
          key: ${{ secrets.SANDBOX_KEY }}
          port: 22
          command_timeout: 10m
          script: |
            cd /opt/clients/ebm_thirdparty_docs
            git pull origin main
            pm2 reload ecosystem.config.js
